on:
  push:
    branches:
      - master

name: shiny_deploy

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: r-lib/actions/setup-r@v1
      - id: rpackages
        name: Install Packages
        run: |
          Rscript -e 'install.packages(c("rsconnect", "dplyr", "shiny", "shinyWidgets", "shinyalert", "shinycssloaders", "assertthat"), dependencies = TRUE)' 
      - id: deploy
        name: Deploy to shinyapps.io
        run: |
          Rscript -e "rsconnect::setAccountInfo(name='adsoncostanzi', token=${{secrets.SHINYAPPS_TOKEN}}, secret=${{secrets.SHINYAPPS_SECRET}})"
          Rscript -e "rsconnect::deployApp(appDir = 'app/', appName = 'soothsayeR')" 