on:
  push:
    branches:
      - master

name: shiny_deploy

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: r-lib/actions/setup-r@master
      - id: rpackages
        name: Install Packages and deploy
        run: |
          install.packages(c("rsconnect", "dplyr", "shiny", "shinyWidgets", "shinyalert", "shinycssloaders", "assertthat"), dependencies = TRUE)
          rsconnect::setAccountInfo("adsoncostanzi", Sys.getenv("SHINYAPPS_TOKEN"), Sys.getenv("SHINYAPPS_SECRET"))
          rsconnect::deployApp(appName = "soothsayeR", appFiles = setdiff(list.files(), "app"))
        shell: Rscript {0}