# Triggered on push 
on: [push]

# Name of the workflow => usethis::use_github_actions_badge("CI-CD")
name: CI-CD

jobs:
  CI-CD:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-

      - name: Check package
        shell: Rscript {0}
        run: |
          install.packages("rcmdcheck")
          rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "warning")

      - name: Deploy to shinyapps.io
        env:
          SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          install.packages(c("rsconnect", "dplyr", "shiny", "shinyWidgets", "shinyalert", "shinycssloaders", "assertthat"), dependencies = TRUE)
          rsconnect::setAccountInfo(Sys.getenv("SHINYAPPS_ACCOUNT"), Sys.getenv("SHINYAPPS_TOKEN"), Sys.getenv("SHINYAPPS_SECRET"))
          rsconnect::deployApp(appName = "soothsayeR", appFiles = setdiff(list.files(), "app"))
        shell: Rscript {0}